### ISSUE TITLE
Issue with offset if client date is greater than server

### ISSUE THREAD

**Issue by JDemonchaux** [StoreConnect/storeconnect-timesync-cpp-client#1]
Hello,
I'm using the Android wrapper for a test app.

It seems that there is an issue in the set_target method in server_date.cpp. If my smartphone date is earlier than the server the offset is correctly computed, but if it is greater the offset always stays at 0.
I think the delta should be in absolute value when comparing it to amortization_threshold.

**Comment by MGasztold** [comment]
@JDemonchaux Thank you for reporting the issue. I agree that lack of `abs` in the delta computation is a bug. I have fixed it in the #2 pull request.

**Comment by MGasztold** [comment]
Before we close this please retest on your side and let me know if it is ok for you now. Thank you.

**Comment by JDemonchaux** [comment]
@MGasztold Working fine right now, thanks!
