### ISSUE TITLE
Android wrapper crashing on 32bits devices

### ISSUE THREAD

**Issue by JDemonchaux** [StoreConnect/storeconnect-timesync-cpp-client#3]
Hello,
I hit trouble while working with the android wrapper on armeabi/armeabi-v7a devices.
Works perfectly fine on arm64 devices, but on 32bits devices it crashes in server_date.cpp:98 at : 
`long long server_date = std::stol(server_date_s);`

I have the following error in Android studio : 
`A/libc: /Volumes/Android/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::out_of_range: stol: out of range" failed`

I've replaced it with `std::stoll` and it seems to work, so the issue might be with `std::stol` messing around with 32bit long limit.

**Comment by MGasztold** [comment]
@JDemonchaux Thank you for reporting this !
